# Generated by Django 5.2.9 on 2026-08-20 00:14

import django.db.models.functions.text
from django.db import migrations, models


def canonicalize_historical_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    database = schema_editor.connection.alias
    users = list(User.objects.using(database).order_by("pk"))
    grouped = {}
    used = {user.email.casefold() for user in users}
    for user in users:
        grouped.setdefault(user.email.casefold(), []).append(user)

    for canonical_email, duplicates in grouped.items():
        winner, *losers = duplicates
        for loser in losers:
            suffix = 0
            while True:
                marker = f"-{suffix}" if suffix else ""
                replacement = f"duplicate-{loser.pk}{marker}@invalid.local"
                if replacement.casefold() not in used:
                    break
                suffix += 1
            used.add(replacement.casefold())
            loser.email = replacement
            loser.is_active = False
            loser.save(update_fields=["email", "is_active"])
        winner.email = canonical_email
        winner.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='emailverificationchallenge',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationchallenge',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            canonicalize_historical_emails,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_casefold'),
        ),
    ]
