# Generated by Django 5.2.16 on 2026-08-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'permissions': (('view_sensitive_fiscal_data', 'Can view unmasked fiscal export data'),)},
        ),
    ]
