# Generated by Django 5.2.17 on 2026-08-20 19:38

import django.contrib.postgres.indexes
from django.db import migrations

from config.migration_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0004_alter_billingprofile_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0003_product_created_at'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='acct_prof_first_trgm', opclasses=('gin_trgm_ops',)),
        ),
        AddIndexConcurrently(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='acct_prof_last_trgm', opclasses=('gin_trgm_ops',)),
        ),
        AddIndexConcurrently(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone'], name='acct_prof_phone_trgm', opclasses=('gin_trgm_ops',)),
        ),
        AddIndexConcurrently(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='acct_user_email_trgm', opclasses=('gin_trgm_ops',)),
        ),
    ]
