# Generated by Django 5.2.9 on 2026-08-20 00:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packaged_weight_grams',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text_value__gt', ''), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('option__isnull', True)), models.Q(('text_value', ''), ('integer_value__isnull', False), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('option__isnull', True)), models.Q(('text_value', ''), ('integer_value__isnull', True), ('decimal_value__isnull', False), ('boolean_value__isnull', True), ('option__isnull', True)), models.Q(('text_value', ''), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', False), ('option__isnull', True)), models.Q(('text_value', ''), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('option__isnull', False)), _connector='OR'), name='attribute_value_exactly_one_storage'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='variant_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='variant_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('packaged_weight_grams__gt', 0)), name='variant_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('length_cm__gt', 0)), name='variant_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('width_cm__gt', 0)), name='variant_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('height_cm__gt', 0)), name='variant_height_positive'),
        ),
    ]
