# Generated by Django 5.2.16 on 2026-08-20 04:28

import django.utils.timezone
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_cost_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                db_default=Now(), default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
