# Generated by Django 5.2.16 on 2026-08-20 06:08

import config.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('import_product', 'Can import products with validation'), ('export_product', 'Can export product administration data'))},
        ),
        migrations.AddField(
            model_name='productmedia',
            name='derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.ImageField(upload_to=config.media.SafeImageUploadTo('catalog'), validators=[config.media.validate_image_upload]),
        ),
    ]
