# Generated by Django 5.2.17 on 2026-08-20 19:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

from config.migration_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('catalog', '0005_productmedia_variant'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='attributevalue',
            index=models.Index(fields=['definition', 'option', 'variant'], name='cat_attr_option_idx'),
        ),
        AddIndexConcurrently(
            model_name='attributevalue',
            index=models.Index(condition=models.Q(('text_value__gt', '')), fields=['definition', 'text_value', 'variant'], name='cat_attr_text_idx'),
        ),
        AddIndexConcurrently(
            model_name='attributevalue',
            index=models.Index(condition=models.Q(('integer_value__isnull', False)), fields=['definition', 'integer_value', 'variant'], name='cat_attr_integer_idx'),
        ),
        AddIndexConcurrently(
            model_name='attributevalue',
            index=models.Index(condition=models.Q(('decimal_value__isnull', False)), fields=['definition', 'decimal_value', 'variant'], name='cat_attr_decimal_idx'),
        ),
        AddIndexConcurrently(
            model_name='attributevalue',
            index=models.Index(condition=models.Q(('boolean_value__isnull', False)), fields=['definition', 'boolean_value', 'variant'], name='cat_attr_boolean_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True), ('is_sellable', True)), fields=['category', '-created_at', '-id'], name='cat_prod_live_cat_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True), ('is_sellable', True)), fields=['brand', '-created_at', '-id'], name='cat_prod_live_brand_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=models.Index(fields=['-created_at', '-id'], name='cat_prod_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', 'description', config='spanish'), name='cat_prod_search_gin'),
        ),
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='cat_prod_name_trgm', opclasses=('gin_trgm_ops',)),
        ),
        AddIndexConcurrently(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], include=('price', 'on_hand'), name='cat_variant_active_idx'),
        ),
        AddIndexConcurrently(
            model_name='productvariant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sku'], name='cat_variant_sku_trgm', opclasses=('gin_trgm_ops',)),
        ),
    ]
