# Generated by Django 5.2.17 on 2026-08-21 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_attributevalue_cat_attr_option_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='max_purchase_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_is_infinite',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('max_purchase_quantity__isnull', True), ('max_purchase_quantity__gt', 0), _connector='OR'), name='cat_variant_purchase_cap_pos'),
        ),
    ]
