"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import type { BillingProfile } from "@/lib/types";

export function FiscalProfiles() {
  const [profiles, setProfiles] = useState<BillingProfile[]>([]); const [values, setValues] = useState({ label: "", legal_name: "", tax_condition: "consumidor_final", cuit: "", is_default: false }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = () => apiRequest<BillingProfile[]>("/billing-profiles/").then(setProfiles).catch((cause) => setError(cause instanceof Error ? cause.message : "No pudimos cargar tus datos fiscales."));
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { await apiRequest<BillingProfile>("/billing-profiles/", { method: "POST", body: JSON.stringify(values) }); setMessage("Perfil fiscal guardado."); setValues({ label: "", legal_name: "", tax_condition: "consumidor_final", cuit: "", is_default: false }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos guardar el perfil."); } };
  return <div className="split-form"><section><h2>Perfiles guardados</h2>{profiles.length ? profiles.map((profile) => <article className="fiscal-row" key={profile.id}><strong>{profile.label}</strong><span>{profile.legal_name}</span><span>{profile.masked_cuit}</span>{profile.is_default && <b>Predeterminado</b>}</article>) : <p>No hay perfiles fiscales guardados.</p>}</section><form className="form-stack" onSubmit={(event) => void submit(event)}><h2>Nuevo perfil fiscal</h2><label htmlFor="fiscal-label">Etiqueta</label><input id="fiscal-label" value={values.label} onChange={(event) => setValues({ ...values, label: event.target.value })} required /><label htmlFor="legal-name">Razón social o nombre</label><input id="legal-name" value={values.legal_name} onChange={(event) => setValues({ ...values, legal_name: event.target.value })} required /><label htmlFor="tax-condition">Condición fiscal</label><select id="tax-condition" value={values.tax_condition} onChange={(event) => setValues({ ...values, tax_condition: event.target.value })}><option value="consumidor_final">Consumidor final</option><option value="monotributista">Monotributista</option><option value="responsable_inscripto">Responsable inscripto</option><option value="exento">Exento</option></select><label htmlFor="cuit">CUIT</label><input id="cuit" inputMode="numeric" value={values.cuit} onChange={(event) => setValues({ ...values, cuit: event.target.value })} required /><label className="check-label"><input type="checkbox" checked={values.is_default} onChange={(event) => setValues({ ...values, is_default: event.target.checked })} /> Usar de forma predeterminada</label>{error && <p className="field-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}<button className="button primary">Guardar perfil</button></form></div>;
}
