# Generated by Django 5.2.17 on 2026-08-20 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('environment', models.CharField(default='sandbox', max_length=24)),
                ('public_config', models.JSONField(blank=True, default=dict)),
                ('sealed_secrets', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_test_status', models.CharField(blank=True, max_length=24)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_configuration_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider',),
                'permissions': (('manage_integrations', 'Can manage provider integrations'), ('test_integrations', 'Can test provider integrations')),
            },
        ),
        migrations.CreateModel(
            name='ManagementAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('resource', models.CharField(max_length=80)),
                ('object_reference', models.CharField(max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
