# Generated by Django 5.2.17 on 2026-08-20 19:38

from django.conf import settings
from django.db import migrations, models

from config.migration_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('backoffice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='managementauditevent',
            index=models.Index(fields=['resource', 'action', '-created_at', '-id'], name='bo_audit_resource_idx'),
        ),
        AddIndexConcurrently(
            model_name='managementauditevent',
            index=models.Index(fields=['actor', '-created_at', '-id'], name='bo_audit_actor_idx'),
        ),
    ]
