# Generated by Django 5.2.17 on 2026-08-26 20:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_variant_stock_limits'),
        ('commerce', '0020_orderitem_unit_cost_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('source', models.CharField(blank=True, max_length=80)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('checkout_starts', models.PositiveIntegerField(default=0)),
                ('delivery_selections', models.PositiveIntegerField(default=0)),
                ('payment_starts', models.PositiveIntegerField(default=0)),
                ('paid_orders', models.PositiveIntegerField(default=0)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'source', 'medium', 'device'], name='an_daily_channel_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'source', 'medium', 'campaign', 'device'), name='an_daily_channel_unique')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('entry_path', models.CharField(max_length=255)),
                ('viewed_product', models.BooleanField(default=False)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('started_checkout', models.BooleanField(default=False)),
                ('selected_delivery', models.BooleanField(default=False)),
                ('started_payment', models.BooleanField(default=False)),
                ('first_converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': (('view_web_analytics', 'Can view web analytics'), ('view_commercial_analytics', 'Can view commercial analytics'), ('export_commercial_analytics', 'Can export commercial analytics')),
                'indexes': [models.Index(fields=['started_at', 'source'], name='an_session_source_idx'), models.Index(fields=['started_at', 'device'], name='an_session_device_idx'), models.Index(fields=['first_converted_at', 'started_at'], name='an_session_conversion_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsOrderAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_attribution', to='commerce.order')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_orders', to='analytics.analyticssession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(db_index=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_conversion', to='commerce.order')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_conversion', to='commerce.paymenttransaction')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='analytics.analyticssession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDailyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('viewing_sessions', models.PositiveIntegerField(default=0)),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('attributed_checkouts', models.PositiveIntegerField(default=0)),
                ('paid_orders', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
                ('product_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'product'], name='an_daily_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'product'), name='an_daily_product_unique')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('product_view', 'Product view'), ('add_to_cart', 'Add to cart'), ('checkout_started', 'Checkout started'), ('delivery_selected', 'Delivery selected'), ('payment_started', 'Payment started')], max_length=32)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.productvariant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.analyticssession')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='an_event_type_time_idx'), models.Index(fields=['session', 'occurred_at'], name='an_event_session_idx'), models.Index(fields=['product', 'occurred_at'], name='an_event_product_idx')],
            },
        ),
    ]
