"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { formatMoney } from "@/lib/format";
import { useCart } from "./cart-provider";
import type { CartLine } from "@/lib/types";

function QuantityField({ line, busy, save }: { line: CartLine; busy: boolean; save: (quantity: number) => Promise<void> }) { const [value, setValue] = useState(line.quantity); useEffect(() => setValue(line.quantity), [line.quantity]); const commit = () => { if (value !== line.quantity) void save(value); }; return <label>Cantidad <input type="number" min={0} max={line.purchase_limit ?? undefined} value={value} disabled={busy} onChange={(event) => { const requested = Math.max(0, Number(event.target.value)); setValue(line.purchase_limit === null ? requested : Math.min(requested, line.purchase_limit)); }} onBlur={commit} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); commit(); } }} /></label>; }
const noticeCopy = (code: string) => code === "price_changed" ? "El precio se actualizó." : "La disponibilidad cambió.";

export function CartPage() {
  const context = useCart(); const [coupon, setCoupon] = useState(""); if (!context || context.loading && !context.cart) return <div className="cart-skeleton" role="status">Actualizando precios y disponibilidad…</div>; const { cart, error, loading, setQuantity, remove, applyCoupon, refresh } = context;
  if (!cart || cart.lines.length === 0) return <div className="empty-state page-empty"><h1>Tu carrito está vacío</h1><p>Cuando agregues un producto, lo vas a encontrar acá.</p><Link className="button primary" href="/catalogo">Explorar catálogo</Link></div>;
  const blocked = cart.lines.some((line) => line.availability !== "available");
  return <div className="cart-page-grid"><section><h1>Tu carrito</h1><p className="page-intro">Revisá cantidades, precios y descuentos antes de continuar.</p>{error && <p role="alert" className="inline-error">{error} <button className="text-button" onClick={() => void refresh()}>Reintentar</button></p>}<div className="cart-page-lines">{cart.lines.map((line) => <article key={line.id}><div><strong>{line.product_name}</strong>{line.variant_name && <p>{line.variant_name}</p>}<p>{formatMoney(line.unit_price)} por unidad</p>{line.notices.map((notice) => <p className="cart-notice" role="status" key={`${notice.code}-${notice.current}`}>{noticeCopy(notice.code)}</p>)}{line.availability !== "available" && <p className="stock-out" role="alert">No disponible en la cantidad solicitada.{!line.stock_is_infinite && ` Stock actual: ${line.available_stock}.`}</p>}</div><QuantityField line={line} busy={loading} save={(quantity) => setQuantity(line.variant_id, quantity)} /><strong>{formatMoney(line.line_total)}</strong><button className="text-button" disabled={loading} onClick={() => void remove(line.variant_id)}>Quitar</button></article>)}</div></section><aside className="cart-summary"><h2>Resumen</h2><dl><div><dt>Subtotal</dt><dd>{formatMoney(cart.subtotal)}</dd></div><div><dt>Descuento</dt><dd>-{formatMoney(cart.discount)}</dd></div><div className="summary-total"><dt>Total</dt><dd>{formatMoney(cart.total)}</dd></div></dl><form onSubmit={(event) => { event.preventDefault(); void applyCoupon(coupon); }}><label htmlFor="coupon">Cupón</label><div><input id="coupon" value={coupon} onChange={(event) => setCoupon(event.target.value)} disabled={loading} /><button className="button secondary" disabled={!coupon || loading}>Aplicar</button></div></form>{blocked ? <p className="inline-error">Corregí la disponibilidad antes de continuar.</p> : <Link href="/checkout" className="button primary wide">Continuar compra</Link>}<Link href="/cuenta/ingresar" className="account-prompt">¿Ya tenés cuenta? Ingresá antes de pagar</Link></aside></div>;
}
