# Generated by Django 5.2.9 on 2026-08-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_image', models.FileField(blank=True, upload_to='landing/desktop')),
                ('mobile_image', models.FileField(blank=True, upload_to='landing/mobile')),
                ('alt_text', models.CharField(max_length=240)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('safe_height_mobile', models.PositiveIntegerField(default=320)),
                ('safe_height_tablet', models.PositiveIntegerField(default=420)),
                ('safe_height_desktop', models.PositiveIntegerField(default=520)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_image', models.FileField(blank=True, upload_to='landing/desktop')),
                ('mobile_image', models.FileField(blank=True, upload_to='landing/mobile')),
                ('alt_text', models.CharField(max_length=240)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('safe_height_mobile', models.PositiveIntegerField(default=320)),
                ('safe_height_tablet', models.PositiveIntegerField(default=420)),
                ('safe_height_desktop', models.PositiveIntegerField(default=520)),
                ('title', models.CharField(max_length=160)),
                ('product_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_image', models.FileField(blank=True, upload_to='landing/desktop')),
                ('mobile_image', models.FileField(blank=True, upload_to='landing/mobile')),
                ('alt_text', models.CharField(max_length=240)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('safe_height_mobile', models.PositiveIntegerField(default=320)),
                ('safe_height_tablet', models.PositiveIntegerField(default=420)),
                ('safe_height_desktop', models.PositiveIntegerField(default=520)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_image', models.FileField(blank=True, upload_to='landing/desktop')),
                ('mobile_image', models.FileField(blank=True, upload_to='landing/mobile')),
                ('alt_text', models.CharField(max_length=240)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('safe_height_mobile', models.PositiveIntegerField(default=320)),
                ('safe_height_tablet', models.PositiveIntegerField(default=420)),
                ('safe_height_desktop', models.PositiveIntegerField(default=520)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(default='mycdigitalizacion', max_length=120)),
                ('announcement', models.CharField(blank=True, max_length=240)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
