# Generated by Django 5.2.9 on 2026-08-20 00:18

import django.core.validators
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, validators=[landing.models.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='landing/desktop', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='focal_x',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='focal_y',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='landing/mobile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='safe_height_desktop',
            field=models.PositiveIntegerField(default=520, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='safe_height_mobile',
            field=models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='safe_height_tablet',
            field=models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, validators=[landing.models.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='landing/desktop', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='focal_x',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='focal_y',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='landing/mobile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='safe_height_desktop',
            field=models.PositiveIntegerField(default=520, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='safe_height_mobile',
            field=models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='safe_height_tablet',
            field=models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, validators=[landing.models.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='landing/desktop', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='focal_x',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='focal_y',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='landing/mobile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='safe_height_desktop',
            field=models.PositiveIntegerField(default=520, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='safe_height_mobile',
            field=models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='safe_height_tablet',
            field=models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, validators=[landing.models.validate_cta_url]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='landing/desktop', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='focal_x',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='focal_y',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='landing/mobile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='safe_height_desktop',
            field=models.PositiveIntegerField(default=520, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='safe_height_mobile',
            field=models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='safe_height_tablet',
            field=models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)]),
        ),
    ]
