# Generated by Django 5.2.16 on 2026-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_heroslide_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_hours',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_label',
            field=models.CharField(default='Retiro en tienda', max_length=120),
        ),
    ]
