# Generated by Django 5.2.16 on 2026-08-20 06:08

import config.media
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_sitesettings_pickup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='desktop_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='interval_ms',
            field=models.PositiveIntegerField(default=6000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='mobile_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='pause_on_reduced_motion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingcollection',
            name='desktop_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='landingcollection',
            name='mobile_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='promotionpopup',
            name='desktop_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='promotionpopup',
            name='dismissible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotionpopup',
            name='display_delay_ms',
            field=models.PositiveIntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AddField(
            model_name='promotionpopup',
            name='frequency',
            field=models.CharField(choices=[('once_session', 'Once per session'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('always', 'Always')], default='once_session', max_length=20),
        ),
        migrations.AddField(
            model_name='promotionpopup',
            name='mobile_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='promotionslide',
            name='desktop_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='promotionslide',
            name='interval_ms',
            field=models.PositiveIntegerField(default=6000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AddField(
            model_name='promotionslide',
            name='mobile_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='promotionslide',
            name='pause_on_reduced_motion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='alt_text',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='alt_text',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='alt_text',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'avif']), config.media.validate_image_upload]),
        ),
    ]
