# Generated by Django 5.2.16 on 2026-08-20 06:57

import config.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_heroslide_desktop_derivatives_heroslide_interval_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='landingcollection',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionpopup',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[config.media.validate_image_upload]),
        ),
    ]
