# Generated by Django 5.2.17 on 2026-08-20 11:51

import config.media
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_heroslide_desktop_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpopup',
            name='version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('branding/favicon'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('branding/logo'), validators=[config.media.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_derivatives',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
