# Generated by Django 5.2.17 on 2026-08-20 19:38

from django.db import migrations, models

from config.migration_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('landing', '0007_promotionpopup_version_sitesettings_favicon_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='heroslide',
            index=models.Index(fields=['enabled', 'order', 'starts_at', 'ends_at'], name='land_hero_schedule_idx'),
        ),
        AddIndexConcurrently(
            model_name='promotionpopup',
            index=models.Index(fields=['enabled', 'order', 'starts_at', 'ends_at'], name='land_popup_schedule_idx'),
        ),
        AddIndexConcurrently(
            model_name='promotionslide',
            index=models.Index(fields=['enabled', 'order', 'starts_at', 'ends_at'], name='land_promo_schedule_idx'),
        ),
    ]
