# Generated by Django 5.2.16 on 2026-08-21 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_heroslide_land_hero_schedule_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
    ]
