# Generated by Django 5.2.17 on 2026-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_sitesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_action',
            field=models.CharField(default='#BD1D59', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_palette',
            field=models.CharField(choices=[('pulso', 'Pulso Comercial'), ('ocean', 'Océano'), ('creative', 'Creativa'), ('natural', 'Natural'), ('custom', 'Personalizada')], default='pulso', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_structure',
            field=models.CharField(default='#020530', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_text',
            field=models.CharField(default='#020530', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_wayfinding',
            field=models.CharField(default='#007F96', max_length=7),
        ),
    ]
