# Generated by Django 5.2.17 on 2026-08-23 15:22

import config.media
import django.core.validators
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_sitesettings_theme_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_image', models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/desktop'), validators=[config.media.validate_image_upload])),
                ('mobile_image', models.ImageField(blank=True, upload_to=config.media.SafeImageUploadTo('landing/mobile'), validators=[config.media.validate_image_upload])),
                ('desktop_derivatives', models.JSONField(blank=True, default=dict, editable=False)),
                ('mobile_derivatives', models.JSONField(blank=True, default=dict, editable=False)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300, validators=[landing.models.validate_cta_url])),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('safe_height_mobile', models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)])),
                ('safe_height_tablet', models.PositiveIntegerField(default=420, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)])),
                ('safe_height_desktop', models.PositiveIntegerField(default=520, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1200)])),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('interval_ms', models.PositiveIntegerField(default=6000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)])),
                ('pause_on_reduced_motion', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['enabled', 'order', 'starts_at', 'ends_at'], name='land_catalog_sched_idx')],
            },
        ),
    ]
