# Generated by Django 5.2.9 on 2026-08-19 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('raw_address', models.CharField(max_length=300)),
                ('normalized_address', models.CharField(blank=True, max_length=300)),
                ('street', models.CharField(max_length=160)),
                ('number', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=16)),
                ('cpa', models.CharField(blank=True, max_length=16)),
                ('locality', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=32)),
                ('apartment', models.CharField(blank=True, max_length=32)),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('', 'None'), ('manual', 'Manual'), ('georef', 'GeoRef')], default='', max_length=24)),
                ('geocode_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
