# Generated by Django 5.2.9 on 2026-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geocode_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PostalLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=120, unique=True)),
                ('postal_code', models.CharField(db_index=True, max_length=4)),
                ('cpa', models.CharField(blank=True, db_index=True, max_length=8)),
                ('locality', models.CharField(max_length=160)),
                ('province', models.CharField(max_length=160)),
                ('provider_summary', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['postal_code', 'locality'], name='locations_p_postal__5d0c88_idx')],
            },
        ),
    ]
