# Generated by Django 5.2.9 on 2026-08-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_staff_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
