# Generated by Django 5.2.9 on 2026-08-20 00:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_cost_and_more'),
        ('commerce', '0003_order_coupon_code_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='coupon_schedule_ordered'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0), models.Q(('discount_type', 'fixed'), models.Q(('discount_type', 'percentage'), ('value__lte', 100)), _connector='OR')), name='coupon_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='promotionrule_schedule_ordered'),
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0), models.Q(('discount_type', 'fixed'), models.Q(('discount_type', 'percentage'), ('value__lte', 100)), _connector='OR')), name='promotionrule_discount_valid'),
        ),
    ]
