# Generated by Django 5.2.9 on 2026-08-20 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_cost_and_more'),
        ('commerce', '0004_alter_coupon_value_alter_promotionrule_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_authenticated_user_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_quantity_positive'),
        ),
    ]
