# Generated by Django 5.2.9 on 2026-08-20 01:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_restrict_append_only_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('inner_length_cm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inner_width_cm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inner_height_cm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tare_weight_grams', models.PositiveIntegerField()),
                ('max_weight_grams', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('needs_attention', 'Needs attention')], default='not_started', max_length=24),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(max_length=64)),
                ('consented_at', models.DateTimeField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('masked_audit', models.JSONField(default=dict)),
                ('staff_diagnostics', models.TextField(blank=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mercadopago', max_length=32)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('expected_collector_id', models.CharField(blank=True, max_length=160)),
                ('live_mode', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_attention', 'Needs attention'), ('refunded', 'Refunded')], default='pending', max_length=24)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('provider_summary', models.JSONField(default=dict)),
                ('staff_diagnostics', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mercadopago', max_length=32)),
                ('event_id', models.CharField(max_length=160)),
                ('request_id', models.CharField(blank=True, max_length=160)),
                ('payment_id', models.CharField(blank=True, max_length=160)),
                ('raw_body_hash', models.CharField(max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(default='received', max_length=24)),
                ('staff_diagnostics', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('stock_restored', models.BooleanField(default=False)),
                ('return_required', models.BooleanField(default=False)),
                ('staff_diagnostics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='commerce.order')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='commerce.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='correo_argentino', max_length=32)),
                ('provider_id', models.CharField(max_length=160, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='created', max_length=64)),
                ('label_url', models.URLField(blank=True, max_length=500)),
                ('provider_summary', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='correo_argentino', max_length=32)),
                ('service', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=8)),
                ('parcels', models.JSONField(default=list)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('cart_fingerprint', models.CharField(max_length=64)),
                ('provider_summary', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.shippingquote'),
        ),
    ]
