# Generated by Django 5.2.9 on 2026-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_notificationattempt_packagebox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='kind',
            field=models.CharField(choices=[('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('sale', 'Sale'), ('release', 'Release'), ('refund', 'Refund')], max_length=16),
        ),
    ]
