# Generated by Django 5.2.9 on 2026-08-20 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_inventorymovement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProviderFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=32)),
                ('staff_diagnostics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
