# Generated by Django 5.2.16 on 2026-08-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_checkout_recovery_and_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentParcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_index', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('parcel_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported')], default='pending', max_length=24)),
                ('provider_summary', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_imports', to='commerce.shipment')),
            ],
            options={
                'ordering': ('parcel_index',),
                'constraints': [models.UniqueConstraint(fields=('shipment', 'parcel_index'), name='unique_shipment_parcel_import_index')],
            },
        ),
    ]
