# Generated by Django 5.2.16 on 2026-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_shipment_parcel_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='available_stock_snapshot',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartline',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
