# Generated by Django 5.2.16 on 2026-08-20 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_cartline_available_stock_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('approve_identity_order', 'Can manually approve order identity'), ('resume_order', 'Can resume an approved order checkout'), ('cancel_order', 'Can cancel an order through the guarded service'), ('refund_order', 'Can refund an order through the guarded service'), ('create_shipment_order', 'Can create an order shipment'), ('refresh_tracking_order', 'Can refresh order tracking'), ('export_order', 'Can export masked order data'), ('view_sensitive_order_data', 'Can export unmasked order data'))},
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('ready_for_pickup', 'Ready for pickup'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='unfulfilled', max_length=24),
        ),
        migrations.CreateModel(
            name='StaffExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=64)),
                ('export_format', models.CharField(max_length=8)),
                ('filters', models.JSONField(default=dict)),
                ('row_count', models.PositiveIntegerField()),
                ('included_sensitive_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
