# Generated by Django 5.2.17 on 2026-08-20 19:38

from django.conf import settings
from django.db import migrations, models

from config.migration_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('catalog', '0006_attributevalue_cat_attr_option_idx_and_more'),
        ('commerce', '0014_inventorymovement_actor_inventorymovement_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(fields=['payment_status', 'fulfillment_status', '-created_at', '-id'], name='comm_order_mgmt_idx'),
        ),
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(fields=['identity_status', '-created_at', '-id'], name='comm_order_identity_idx'),
        ),
        AddIndexConcurrently(
            model_name='promotionrule',
            index=models.Index(fields=['enabled', 'starts_at', 'ends_at'], name='comm_promo_schedule_idx'),
        ),
        AddIndexConcurrently(
            model_name='stockreservation',
            index=models.Index(fields=['variant', 'status', 'expires_at'], name='comm_res_active_idx'),
        ),
    ]
