# Generated by Django 5.2.17 on 2026-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_order_comm_order_mgmt_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='tracks_inventory',
            field=models.BooleanField(db_default=True, default=True, editable=False),
        ),
    ]
