# Generated by Django 5.2.17 on 2026-08-21 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_reservation_inventory_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('max_redemptions__isnull', True), ('max_redemptions__gte', 1), _connector='OR'), name='coupon_max_redemptions_positive'),
        ),
    ]
