# Generated by Django 5.2.17 on 2026-08-21 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_coupon_max_redemptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], default='reserved', max_length=16)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='commerce.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemption', to='commerce.order')),
            ],
            options={
                'indexes': [models.Index(fields=['coupon', 'status', 'expires_at'], name='comm_coupon_usage_idx')],
            },
        ),
    ]
