# Generated by Django 5.2.17 on 2026-08-21 15:34

from django.db import migrations, models


def mark_existing_shipping_costs_ready(apps, schema_editor):
    del schema_editor
    Order = apps.get_model("commerce", "Order")
    Order.objects.filter(shipping_quote__isnull=False).update(shipping_cost_status="ready")


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_couponredemption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('approve_identity_order', 'Can manually approve order identity'), ('resume_order', 'Can resume an approved order checkout'), ('cancel_order', 'Can cancel an order through the guarded service'), ('refund_order', 'Can refund an order through the guarded service'), ('create_shipment_order', 'Can create an order shipment'), ('refresh_tracking_order', 'Can refresh order tracking'), ('set_shipping_cost_order', 'Can set an agreed shipping cost'), ('export_order', 'Can export masked order data'), ('view_sensitive_order_data', 'Can export unmasked order data'))},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending_agreement', 'Pending agreement'), ('ready', 'Ready')], default='not_required', max_length=24),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='amount_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_shipping_costs_ready, migrations.RunPython.noop),
    ]
