# Generated by Django 5.2.17 on 2026-08-26 20:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_alter_order_options_order_shipping_cost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
