"use client";

import { FunnelSimple, X } from "@phosphor-icons/react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { CatalogResponse, Category } from "@/lib/types";
import { buildCatalogQuery, type CatalogState } from "@/lib/catalog-query";
import { ProductCard } from "@/components/product/product-card";

export function CatalogBrowser({ response, categories, initial }: { response: CatalogResponse; categories: Category[]; initial: CatalogState }) {
  const router = useRouter(); const triggerRef = useRef<HTMLButtonElement>(null); const sheetRef = useRef<HTMLElement>(null); const resultsRef = useRef<HTMLElement>(null); const [filtersOpen, setFiltersOpen] = useState(false); const [minPrice, setMinPrice] = useState(initial.minPrice?.toString() ?? ""); const [maxPrice, setMaxPrice] = useState(initial.maxPrice?.toString() ?? "");
  const apply = (next: CatalogState) => { const query = buildCatalogQuery(next); router.push(query ? `/catalogo?${query}` : "/catalogo"); };
  const close = () => { setFiltersOpen(false); requestAnimationFrame(() => triggerRef.current?.focus()); };
  useEffect(() => {
    if (!filtersOpen) return; const background = [...document.querySelectorAll<HTMLElement>(".site-header, .trust-rail, .site-footer, .breadcrumb, .catalog-title")]; background.forEach((item) => item.setAttribute("inert", "")); resultsRef.current?.setAttribute("inert", ""); sheetRef.current?.querySelector<HTMLElement>("button, input, select")?.focus();
    const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); close(); return; } if (event.key !== "Tab" || !sheetRef.current) return; const nodes = [...sheetRef.current.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), [href]')]; const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } };
    document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); background.forEach((item) => item.removeAttribute("inert")); resultsRef.current?.removeAttribute("inert"); };
  }, [filtersOpen]);
  const depth = useMemo(() => { const byId = new Map(categories.map((item) => [item.id, item])); return new Map(categories.map((item) => { let level = 0; let parent = item.parent_id ? byId.get(item.parent_id) : undefined; while (parent && level < 5) { level += 1; parent = parent.parent_id ? byId.get(parent.parent_id) : undefined; } return [item.id, level]; })); }, [categories]);
  const toggle = (values: string[] | undefined, value: string) => values?.includes(value) ? values.filter((item) => item !== value) : [...(values ?? []), value];
  const chips: Array<{ label: string; clear: () => void }> = [];
  if (initial.q) chips.push({ label: `Búsqueda: ${initial.q}`, clear: () => apply({ ...initial, q: undefined, page: 1 }) });
  if (initial.category) chips.push({ label: categories.find((item) => item.slug === initial.category)?.name ?? initial.category, clear: () => apply({ ...initial, category: undefined, page: 1 }) });
  initial.brands?.forEach((brand) => chips.push({ label: `Marca: ${brand}`, clear: () => apply({ ...initial, brands: initial.brands?.filter((item) => item !== brand), page: 1 }) }));
  if (initial.inStock) chips.push({ label: "Con stock", clear: () => apply({ ...initial, inStock: undefined, page: 1 }) });
  if (initial.onOffer) chips.push({ label: "En oferta", clear: () => apply({ ...initial, onOffer: undefined, page: 1 }) });
  Object.entries(initial.attributes ?? {}).forEach(([name, values]) => values.forEach((value) => chips.push({ label: `${name}: ${value}`, clear: () => apply({ ...initial, attributes: { ...initial.attributes, [name]: values.filter((item) => item !== value) }, page: 1 }) })));
  return <div className="catalog-layout">
    <button ref={triggerRef} className="filter-trigger button secondary" onClick={() => setFiltersOpen(true)} aria-expanded={filtersOpen} aria-controls="catalog-filters"><FunnelSimple size={19} /> Filtrar</button>
    <aside ref={sheetRef} id="catalog-filters" className={`filters ${filtersOpen ? "is-open" : ""}`} aria-label="Filtros de catálogo" role={filtersOpen ? "dialog" : undefined} aria-modal={filtersOpen || undefined}>
      <div className="filters-title"><h2>Filtrar</h2><button className="icon-button filter-close" aria-label="Cerrar filtros" onClick={close}><X size={20} /></button></div>
      <label htmlFor="category-filter">Categoría</label><select id="category-filter" value={initial.category ?? ""} onChange={(event) => apply({ ...initial, category: event.target.value || undefined, page: 1 })}><option value="">Todas</option>{categories.map((category) => <option key={category.id} value={category.slug}>{`${"· ".repeat(depth.get(category.id) ?? 0)}${category.name}`}</option>)}</select>
      {response.facets.brands.length > 0 && <fieldset><legend>Marca</legend>{response.facets.brands.map((option) => <label className="facet-option" key={option.slug}><input type="checkbox" checked={initial.brands?.includes(option.slug) ?? false} onChange={() => apply({ ...initial, brands: toggle(initial.brands, option.slug), page: 1 })} /> {option.name} <small>({option.count})</small></label>)}</fieldset>}
      <form className="price-filter" onSubmit={(event) => { event.preventDefault(); apply({ ...initial, minPrice: minPrice ? Number(minPrice) : undefined, maxPrice: maxPrice ? Number(maxPrice) : undefined, page: 1 }); }}><fieldset><legend>Precio</legend><div className="field-pair"><div><label htmlFor="min-price">Desde</label><input id="min-price" inputMode="numeric" value={minPrice} onChange={(event) => setMinPrice(event.target.value)} /></div><div><label htmlFor="max-price">Hasta</label><input id="max-price" inputMode="numeric" value={maxPrice} onChange={(event) => setMaxPrice(event.target.value)} /></div></div><button className="button secondary">Aplicar precio</button></fieldset></form>
      <fieldset><legend>Disponibilidad</legend><label className="facet-option"><input type="checkbox" checked={initial.inStock ?? false} onChange={(event) => apply({ ...initial, inStock: event.target.checked || undefined, page: 1 })} /> Con stock <small>({response.facets.availability.in_stock})</small></label><label className="facet-option"><input type="checkbox" checked={initial.onOffer ?? false} onChange={(event) => apply({ ...initial, onOffer: event.target.checked || undefined, page: 1 })} /> En oferta <small>({response.facets.offer.on_offer})</small></label></fieldset>
      {response.facets.attributes.map((facet) => <fieldset key={facet.slug}><legend>{facet.name}</legend>{facet.values.map((option) => { const value = String(option.value); return <label className="facet-option" key={value}><input type="checkbox" checked={initial.attributes?.[facet.slug]?.includes(value) ?? false} onChange={() => apply({ ...initial, attributes: { ...initial.attributes, [facet.slug]: toggle(initial.attributes?.[facet.slug], value) }, page: 1 })} /> {option.label} <small>({option.count})</small></label>; })}</fieldset>)}
      {chips.length > 0 && <button type="button" className="text-button" onClick={() => apply({ sort: initial.sort })}>Limpiar filtros</button>}
    </aside>
    <section ref={resultsRef} className="catalog-results" aria-live="polite"><div className="catalog-toolbar"><p><strong>{response.count}</strong> {response.count === 1 ? "producto encontrado" : "productos encontrados"}</p><label htmlFor="sort">Ordenar</label><select id="sort" value={initial.sort ?? "relevance"} onChange={(event) => apply({ ...initial, sort: event.target.value as CatalogState["sort"], page: 1 })}><option value="relevance">Relevancia</option><option value="price_asc">Menor precio</option><option value="price_desc">Mayor precio</option><option value="discount_desc">Mayor descuento</option><option value="newest">Más nuevos</option></select></div>{chips.length > 0 && <div className="filter-chips" aria-label="Filtros aplicados">{chips.map((chip) => <button key={chip.label} onClick={chip.clear}>{chip.label} <X size={15} aria-hidden /></button>)}</div>}{response.results.length ? <div className={`product-grid count-${Math.min(response.results.length, 4)}`}>{response.results.map((product, index) => <ProductCard product={product} key={product.id} priority={index < 2} />)}</div> : <div className="empty-state catalog-empty"><h2>No encontramos resultados</h2><p>Probá con otra búsqueda o quitá alguno de los filtros.</p><button className="button primary" onClick={() => apply({})}>Ver todo el catálogo</button></div>}{(response.previous || response.next) && <nav className="pagination" aria-label="Páginas del catálogo"><button disabled={!response.previous} onClick={() => apply({ ...initial, page: Math.max(1, (initial.page ?? 1) - 1) })}>Anterior</button><span>Página {initial.page ?? 1}</span><button disabled={!response.next} onClick={() => apply({ ...initial, page: (initial.page ?? 1) + 1 })}>Siguiente</button></nav>}</section>
  </div>;
}
