import http from "node:http";
import { readFileSync } from "node:fs";
import { URL } from "node:url";

const categories = [{ id: 1, name: "Tecnología", slug: "tecnologia", parent_id: null }, { id: 2, name: "Papelería", slug: "papeleria", parent_id: null }, { id: 3, name: "Cuadernos", slug: "cuadernos", parent_id: 2 }, { id: 4, name: "Hogar", slug: "hogar", parent_id: null }];
const pricing = { list_price: "15000.00", effective_price: "12500.00", discount_amount: "2500.00", discount_percentage: "16.67", on_offer: true };
const variant = { id: 11, sku: "CUA-A5-AZ", name: "Azul", price: "15000.00", available_stock: 8, packaged_weight_grams: 300, length_cm: "21.00", width_cm: "15.00", height_cm: "2.00", volume_cm3: "630.000000", attributes: [{ name: "Color", slug: "color", type: "option", value: "azul" }], pricing };
const products = [{ id: 7, name: "Cuaderno A5", slug: "cuaderno-a5", description: "Cuaderno de tapa rígida para estudio y oficina.", category: categories[2], brand: { name: "Sur", slug: "sur" }, available_stock: 8, effective_price: "12500.00", on_offer: true, variants: [variant], media: [{ file: "/media/catalog/cuaderno.png", alt_text: "Cuadernos y útiles en tonos azul y cyan", order: 1 }] }];
const facets = { categories: [{ name: "Papelería", slug: "papeleria", count: 1, children: [{ name: "Cuadernos", slug: "cuadernos", count: 1, children: [] }] }], brands: [{ name: "Sur", slug: "sur", count: 1 }], price: { min: "12500.00", max: "12500.00" }, availability: { in_stock: 1, out_of_stock: 0 }, offer: { on_offer: 1, regular: 0 }, attributes: [{ name: "Color", slug: "color", type: "option", values: [{ value: "azul", label: "Azul", count: 1 }] }] };
const addressBase = { id: 2, label: "Casa", raw_address: "Av. Corrientes 1234, CABA", normalized_address: "Avenida Corrientes 1234", street: "Av. Corrientes", number: "1234", postal_code: "1043", cpa: "C1043", locality: "CABA", province: "CABA", latitude: "-34.6037000", longitude: "-58.3816000", floor: "", apartment: "", reference: "", notes: "", geocode_source: "georef", geocode_confidence: "0.950", geocode_summary: {}, needs_review: false, reviewed_at: "2026-08-20T00:05:00Z", created_at: "2026-08-20T00:00:00Z", updated_at: "2026-08-20T00:05:00Z" };
const billing = [{ id: 3, label: "Personal", legal_name: "Cliente sintético de prueba", tax_condition: "consumidor_final", is_default: true, masked_cuit: "20-********-3" }];
const image = readFileSync(new URL("../public/campaigns/pulso-libreria-collection.png", import.meta.url));

let state;
const reset = () => { state = { csrf: "csrf-1", loggedIn: true, cmsError: false, address: { ...addressBase }, customer: { id: 5, email: "cliente@example.com", email_verified_at: "2026-08-20T10:00:00Z", profile: { first_name: "Ana", last_name: "Pérez", phone: "1155551234" }, masked_dni: "••••5678", masked_cuit: "" }, cart: { lines: [], subtotal: "0.00", discount: "0.00", total: "0.00", cart_token: "mock-cart-token", coupon: null }, payments: ["pending", "pending", "approved"], requests: [] }; };
reset();
const json = (response, status, body, headers = {}) => { response.writeHead(status, { "content-type": "application/json", ...headers }); response.end(body === undefined ? "" : JSON.stringify(body)); };
const read = (request) => new Promise((resolve) => { let data = ""; request.on("data", (chunk) => { data += chunk; }); request.on("end", () => { try { resolve(data ? JSON.parse(data) : {}); } catch { resolve({}); } }); });
const unsafe = (method) => !["GET", "HEAD", "OPTIONS"].includes(method ?? "GET");
const validateCsrf = (request, response) => { if (unsafe(request.method) && request.headers["x-csrftoken"] !== state.csrf) { json(response, 403, { code: "csrf_failed", detail: "CSRF token rotated." }); return false; } return true; };
const line = (quantity) => ({ id: 1, variant_id: 11, sku: "CUA-A5-AZ", name: "Cuaderno A5 · Azul", quantity, unit_price: "12500.00", line_subtotal: `${12500 * quantity}.00`, line_discount: "0.00", line_total: `${12500 * quantity}.00`, availability: "available", available_stock: 8, notices: [] });
const setCart = (quantity) => { state.cart = quantity > 0 ? { ...state.cart, lines: [line(quantity)], subtotal: `${12500 * quantity}.00`, total: `${12500 * quantity}.00` } : { ...state.cart, lines: [], subtotal: "0.00", total: "0.00" }; return state.cart; };

http.createServer(async (request, response) => {
  const url = new URL(request.url, "http://127.0.0.1:4010"); const path = url.pathname.replace(/\/$/, "");
  if (path.startsWith("/media/")) { response.writeHead(200, { "content-type": "image/png", "cache-control": "public,max-age=3600" }); response.end(image); return; }
  if (path === "/__control") { const body = await read(request); if (body.reset) reset(); Object.assign(state, body); return json(response, 200, state); }
  if (path === "/__requests") return json(response, 200, state.requests);
  if (request.method === "OPTIONS") return json(response, 204);
  const body = unsafe(request.method) ? await read(request) : {};
  state.requests.push({ method: request.method, path, body, csrf: request.headers["x-csrftoken"] ?? null, cookie: request.headers.cookie ?? "" });
  if (path === "/api/v1/storefront/home") { if (state.cmsError) return json(response, 503, { code: "provider_down", detail: "CMS no disponible" }); return json(response, 200, { settings: { public_name: "mycdigitalizacion", announcement: "", contact_email: "", pickup_enabled: true, pickup_label: "Retiro central", pickup_address: "Av. Corrientes 1234", pickup_hours: "Lunes a viernes de 10 a 18" }, hero_slides: [{ id: 1, title: "Todo lo que buscás, en un solo lugar", body: "Tecnología, papelería, hogar y más para descubrir.", alt_text: "Cuaderno, botella y accesorios de escritorio en azul, blanco y magenta", desktop_image_url: "/media/cms/hero.png", mobile_image_url: "/media/cms/hero-mobile.png", cta_label: "Explorar catálogo", cta_url: "/catalogo", focal_x: 58, focal_y: 50, safe_height_mobile: 390, safe_height_tablet: 520, safe_height_desktop: 570, starts_at: null, ends_at: null, order: 1 }], promotion_slides: [], collections: [{ id: 4, title: "Ideas para estudio y oficina", body: "Una selección publicada por el equipo de la tienda.", alt_text: "Cuadernos y útiles para estudio", desktop_image_url: "/media/cms/collection.png", mobile_image_url: "", cta_label: "Explorar papelería", cta_url: "/catalogo?category=papeleria", focal_x: 50, focal_y: 50, safe_height_mobile: 420, safe_height_tablet: 500, safe_height_desktop: 520, starts_at: null, ends_at: null, order: 1, product_ids: [7] }], promotion_popups: [] }); }
  if (path === "/api/v1/categories") return json(response, 200, categories);
  if (path === "/api/v1/products" || path === "/api/v1/search") return json(response, 200, { count: products.length, next: null, previous: null, results: products, facets });
  if (path === "/api/v1/products/cuaderno-a5") return json(response, 200, products[0]);
  if (path === "/api/v1/auth/csrf") return json(response, 200, { csrf_token: state.csrf }, { "set-cookie": `csrftoken=${state.csrf}; Path=/; SameSite=Lax` });
  if (path === "/api/v1/auth/login" && request.method === "POST") { if (!validateCsrf(request, response)) return; state.loggedIn = true; state.csrf = "csrf-2"; return json(response, 200, state.customer, { "set-cookie": "csrftoken=csrf-2; Path=/; SameSite=Lax" }); }
  if (path === "/api/v1/auth/logout" && request.method === "POST") { if (!validateCsrf(request, response)) return; state.loggedIn = false; state.csrf = "csrf-3"; return json(response, 204, undefined, { "set-cookie": "csrftoken=csrf-3; Path=/; SameSite=Lax" }); }
  if (path === "/api/v1/auth/register" && request.method === "POST") { if (!validateCsrf(request, response)) return; if (!body.first_name || !body.last_name || !body.phone) return json(response, 400, { first_name: ["Requerido para la tienda."], last_name: ["Requerido para la tienda."], phone: ["Requerido para la tienda."] }); return json(response, 201, { ...state.customer, email: body.email, profile: { first_name: body.first_name, last_name: body.last_name, phone: body.phone }, masked_dni: "" }); }
  if (path === "/api/v1/auth/email-verify" && request.method === "POST") { if (!validateCsrf(request, response)) return; return json(response, 200, { status: "verified" }); }
  if (path === "/api/v1/customers/me" && request.method === "GET") return json(response, 200, state.customer);
  if (path === "/api/v1/customers/me" && request.method === "PATCH") { if (!validateCsrf(request, response)) return; state.customer = { ...state.customer, profile: { first_name: body.first_name ?? state.customer.profile.first_name, last_name: body.last_name ?? state.customer.profile.last_name, phone: body.phone ?? state.customer.profile.phone }, masked_dni: body.dni ? `••••${String(body.dni).replace(/\D/g, "").slice(-4)}` : state.customer.masked_dni }; return json(response, 200, state.customer); }
  if (path === "/api/v1/cart") { if (request.method !== "GET" && !validateCsrf(request, response)) return; if (request.method === "POST" && body.variant_id) setCart(body.quantity); if (request.method === "PATCH") setCart(body.quantity); if (request.method === "DELETE") setCart(0); return json(response, request.method === "POST" ? 201 : 200, state.cart); }
  if (path === "/api/v1/identity/status") return json(response, 200, { status: "approved", can_validate: false });
  if (path === "/api/v1/identity/validate") { if (!validateCsrf(request, response)) return; return json(response, 200, { status: "approved", can_validate: false }); }
  if (path === "/api/v1/locations/postal-lookup") return json(response, 200, [{ postal_code: "1043", cpa: "C1043", locality: "CABA", province: "CABA" }]);
  if (path === "/api/v1/addresses" && request.method === "GET") return json(response, 200, [state.address]);
  if (path === "/api/v1/addresses" && request.method === "POST") { if (!validateCsrf(request, response)) return; state.address = { ...addressBase, ...body, needs_review: true, reviewed_at: null }; return json(response, 201, state.address); }
  if (path === "/api/v1/locations/geocode") { if (!validateCsrf(request, response)) return; state.address = { ...state.address, latitude: "-34.6037000", longitude: "-58.3816000", needs_review: true, reviewed_at: null, geocode_source: "georef" }; return json(response, 200, state.address); }
  if (path === "/api/v1/locations/reverse-geocode") { if (!validateCsrf(request, response)) return; state.address = { ...state.address, latitude: String(body.latitude), longitude: String(body.longitude), normalized_address: "Avenida Rivadavia 2000", geocode_source: "manual", needs_review: true, reviewed_at: null }; return json(response, 200, { address: state.address, location: { formatted_address: "Avenida Rivadavia 2000, CABA" } }); }
  if (path === `/api/v1/addresses/${state.address.id}/confirm`) { if (!validateCsrf(request, response)) return; if (!['written', 'reverse'].includes(body.address_choice)) return json(response, 400, { address_choice: ["Opción inválida"] }); state.address = { ...state.address, latitude: body.latitude, longitude: body.longitude, needs_review: false, reviewed_at: "2026-08-20T11:00:00Z" }; return json(response, 200, state.address); }
  if (path === "/api/v1/billing-profiles") return json(response, 200, billing);
  if (path === "/api/v1/orders") return json(response, 200, []);
  if (path === "/api/v1/shipping/quote") { if (!validateCsrf(request, response)) return; return json(response, 200, { public_id: "22222222-2222-4222-8222-222222222222", service: "correo_argentino", parcels: [], base_amount: "4500.00", surcharge_amount: "0.00", total_amount: "4500.00", currency: "ARS", expires_at: "2026-08-20T23:59:00Z" }); }
  if (path === "/api/v1/checkout") { if (!validateCsrf(request, response)) return; return json(response, 202, { order_id: "33333333-3333-4333-8333-333333333333", identity_status: "pending_review", payment_status: "pending", checkout_url: "" }); }
  if (path.startsWith("/api/v1/payments/") && path.endsWith("/status")) return json(response, 200, { status: state.payments.length > 1 ? state.payments.shift() : state.payments[0] ?? "pending" });
  if (path.startsWith("/api/v1/orders/")) return json(response, 200, { public_id: path.split("/").at(-1), identity_status: "verified", payment_status: "paid", fulfillment_status: "shipped", fulfillment_method: "shipping", customer_snapshot: {}, address_snapshot: { raw_address: "Av. Corrientes 1234, CABA" }, fiscal_snapshot: billing[0], coupon_code_snapshot: "", subtotal_snapshot: "12500.00", discount_snapshot: "0.00", shipping_amount_snapshot: "4500.00", total_snapshot: "17000.00", items: [{ product_name_snapshot: "Cuaderno A5", variant_name_snapshot: "Azul", sku_snapshot: "CUA-A5-AZ", quantity: 1, unit_price_snapshot: "12500.00", discount_snapshot: "0.00", line_total_snapshot: "12500.00" }], timeline: [{ status: "order_created", label: "Pedido creado", occurred_at: "2026-08-20T10:00:00Z" }, { status: "payment_paid", label: "Pago confirmado", occurred_at: "2026-08-20T10:05:00Z" }, { status: "fulfillment_shipped", label: "Pedido despachado", occurred_at: "2026-08-20T12:00:00Z" }], shipment: { carrier: "Correo Argentino", tracking_number: "CP123AR", status: "in_transit", updated_at: "2026-08-20T12:00:00Z" }, pickup_information: null, created_at: "2026-08-20T10:00:00Z" });
  return json(response, 404, { code: "not_found", detail: "Mock route not found" });
}).listen(4010, "127.0.0.1");
