# Generated by Django 5.2.17 on 2026-08-23 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_variant_stock_limits'),
        ('commerce', '0019_alter_order_options_order_shipping_cost_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('consultation', 'Consulta'), ('problem', 'Problema')], max_length=16)),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('waiting_staff', 'Waiting staff'), ('waiting_customer', 'Waiting customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_email_normalized', models.CharField(blank=True, db_index=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('recovery_code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('staff_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupportGuestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_accesses', to='support.supportcase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_accesses', to='support.supportguestsession')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('customer', 'Customer'), ('guest', 'Guest'), ('staff', 'Staff')], max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportcase')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('detected_mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_support_attachments', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['kind', 'status', 'priority', '-updated_at', '-id'], name='sup_case_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['assigned_to', '-updated_at', '-id'], name='sup_case_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['contact_email_normalized'], name='sup_case_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportguestaccess',
            constraint=models.UniqueConstraint(fields=('session', 'case'), name='sup_guest_access_uniq'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['case', 'created_at', 'id'], name='sup_message_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(fields=('case', 'idempotency_key'), name='sup_message_case_idem_uniq'),
        ),
    ]
