# Generated by Django 5.2.17 on 2026-08-23 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_variant_stock_limits'),
        ('commerce', '0019_alter_order_options_order_shipping_cost_status_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supportcase',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('consultation', 'problem'))), name='sup_case_kind_valid'),
        ),
    ]
