from django.urls import path

from analytics.management_views import (
    ManagementCommercialAnalyticsExportView,
    ManagementCommercialAnalyticsView,
    ManagementWebAnalyticsView,
)
from backoffice.access_views import (
    ManagementAuditListView,
    ManagementRoleListView,
    ManagementStaffDetailView,
    ManagementStaffListCreateView,
)
from backoffice.catalog_views import (
    AttributeDefinitionDetailView,
    AttributeDefinitionListCreateView,
    BrandDetailView,
    BrandListCreateView,
    CategoryDetailView,
    CategoryListCreateView,
    InventoryListView,
    ProductDetailView,
    ProductListCreateView,
    ProductMediaDetailView,
    ProductMediaListCreateView,
    StockAdjustmentView,
)
from backoffice.content_views import (
    ContentDetailView,
    ContentListCreateView,
    CouponDetailView,
    CouponListCreateView,
    PromotionRuleDetailView,
    PromotionRuleListCreateView,
    PromotionScopeOptionsView,
)
from backoffice.oauth_views import (
    MercadoPagoOAuthDisconnectView,
    MercadoPagoOAuthStartView,
    MercadoPagoOwnAccountConnectView,
)
from backoffice.operations_views import (
    ManagementCustomerAddressDetailView,
    ManagementCustomerDetailView,
    ManagementCustomerListView,
    ManagementOrderActionView,
    ManagementOrderDetailView,
    ManagementOrderListView,
    PackageBoxDetailView,
    PackageBoxListCreateView,
)
from backoffice.views import (
    GeneralSettingsView,
    IntegrationDetailView,
    IntegrationListView,
    IntegrationTestView,
    ManagementDashboardView,
    ManagementSessionView,
)
from support.management_views import (
    ManagementSupportAssigneeListView,
    ManagementSupportAttachmentDownloadView,
    ManagementSupportCaseDetailView,
    ManagementSupportCaseListView,
    ManagementSupportCategoryDetailView,
    ManagementSupportCategoryListCreateView,
    ManagementSupportMessageCreateView,
    ManagementSupportSummaryView,
)

urlpatterns = [
    path(
        "analytics/web/",
        ManagementWebAnalyticsView.as_view(),
        name="management-analytics-web",
    ),
    path(
        "analytics/commercial/",
        ManagementCommercialAnalyticsView.as_view(),
        name="management-analytics-commercial",
    ),
    path(
        "analytics/commercial/export.csv",
        ManagementCommercialAnalyticsExportView.as_view(),
        name="management-analytics-commercial-export",
    ),
    path(
        "support/categories/",
        ManagementSupportCategoryListCreateView.as_view(),
        name="management-support-categories",
    ),
    path(
        "support/categories/<int:pk>/",
        ManagementSupportCategoryDetailView.as_view(),
        name="management-support-category-detail",
    ),
    path(
        "support/assignees/",
        ManagementSupportAssigneeListView.as_view(),
        name="management-support-assignees",
    ),
    path(
        "support/cases/",
        ManagementSupportCaseListView.as_view(),
        name="management-support-cases",
    ),
    path(
        "support/cases/<uuid:public_id>/",
        ManagementSupportCaseDetailView.as_view(),
        name="management-support-case-detail",
    ),
    path(
        "support/cases/<uuid:public_id>/messages/",
        ManagementSupportMessageCreateView.as_view(),
        name="management-support-message-create",
    ),
    path(
        "support/summary/",
        ManagementSupportSummaryView.as_view(),
        name="management-support-summary",
    ),
    path(
        "support/attachments/<uuid:public_id>/",
        ManagementSupportAttachmentDownloadView.as_view(),
        name="management-support-attachment-download",
    ),
    path("session/", ManagementSessionView.as_view(), name="management-session"),
    path("dashboard/", ManagementDashboardView.as_view(), name="management-dashboard"),
    path("integrations/", IntegrationListView.as_view(), name="management-integrations"),
    path(
        "integrations/<slug:provider>/",
        IntegrationDetailView.as_view(),
        name="management-integration-detail",
    ),
    path(
        "integrations/<slug:provider>/test/",
        IntegrationTestView.as_view(),
        name="management-integration-test",
    ),
    path(
        "integrations/mercadopago/connect/",
        MercadoPagoOwnAccountConnectView.as_view(),
        name="management-mercadopago-connect-own-account",
    ),
    path(
        "integrations/mercadopago/oauth/start/",
        MercadoPagoOAuthStartView.as_view(),
        name="management-mercadopago-oauth-start",
    ),
    path(
        "integrations/mercadopago/oauth/disconnect/",
        MercadoPagoOAuthDisconnectView.as_view(),
        name="management-mercadopago-oauth-disconnect",
    ),
    path(
        "settings/general/",
        GeneralSettingsView.as_view(),
        name="management-general-settings",
    ),
    path("products/", ProductListCreateView.as_view(), name="management-products"),
    path(
        "products/<int:pk>/",
        ProductDetailView.as_view(),
        name="management-product-detail",
    ),
    path(
        "products/<int:pk>/media/",
        ProductMediaListCreateView.as_view(),
        name="management-product-media",
    ),
    path(
        "products/<int:pk>/media/<int:media_pk>/",
        ProductMediaDetailView.as_view(),
        name="management-product-media-detail",
    ),
    path("categories/", CategoryListCreateView.as_view(), name="management-categories"),
    path(
        "categories/<int:pk>/",
        CategoryDetailView.as_view(),
        name="management-category-detail",
    ),
    path("brands/", BrandListCreateView.as_view(), name="management-brands"),
    path(
        "brands/<int:pk>/",
        BrandDetailView.as_view(),
        name="management-brand-detail",
    ),
    path(
        "attributes/",
        AttributeDefinitionListCreateView.as_view(),
        name="management-attributes",
    ),
    path(
        "attributes/<int:pk>/",
        AttributeDefinitionDetailView.as_view(),
        name="management-attribute-detail",
    ),
    path("inventory/", InventoryListView.as_view(), name="management-inventory"),
    path(
        "variants/<int:pk>/adjust-stock/",
        StockAdjustmentView.as_view(),
        name="management-stock-adjustment",
    ),
    path("orders/", ManagementOrderListView.as_view(), name="management-orders"),
    path(
        "orders/<uuid:public_id>/",
        ManagementOrderDetailView.as_view(),
        name="management-order-detail",
    ),
    path(
        "orders/<uuid:public_id>/actions/",
        ManagementOrderActionView.as_view(),
        name="management-order-actions",
    ),
    path(
        "customers/", ManagementCustomerListView.as_view(), name="management-customers"
    ),
    path(
        "customers/<int:pk>/",
        ManagementCustomerDetailView.as_view(),
        name="management-customer-detail",
    ),
    path(
        "customers/<int:pk>/addresses/<int:address_pk>/",
        ManagementCustomerAddressDetailView.as_view(),
        name="management-customer-address-detail",
    ),
    path(
        "shipping/boxes/",
        PackageBoxListCreateView.as_view(),
        name="management-shipping-boxes",
    ),
    path(
        "shipping/boxes/<int:pk>/",
        PackageBoxDetailView.as_view(),
        name="management-shipping-box-detail",
    ),
    path(
        "content/<slug:content_type>/",
        ContentListCreateView.as_view(),
        name="management-content-list",
    ),
    path(
        "content/<slug:content_type>/<int:pk>/",
        ContentDetailView.as_view(),
        name="management-content-detail",
    ),
    path(
        "promotions/rules/",
        PromotionRuleListCreateView.as_view(),
        name="management-promotion-rules",
    ),
    path(
        "promotions/scope-options/",
        PromotionScopeOptionsView.as_view(),
        name="management-promotion-scope-options",
    ),
    path(
        "promotions/rules/<int:pk>/",
        PromotionRuleDetailView.as_view(),
        name="management-promotion-rule-detail",
    ),
    path(
        "promotions/coupons/",
        CouponListCreateView.as_view(),
        name="management-coupons",
    ),
    path(
        "promotions/coupons/<int:pk>/",
        CouponDetailView.as_view(),
        name="management-coupon-detail",
    ),
    path("users/", ManagementStaffListCreateView.as_view(), name="management-users"),
    path(
        "users/<int:pk>/",
        ManagementStaffDetailView.as_view(),
        name="management-user-detail",
    ),
    path("roles/", ManagementRoleListView.as_view(), name="management-roles"),
    path("audit/", ManagementAuditListView.as_view(), name="management-audit"),
]
